name: Weekly Fixture Rotation

on:
  schedule:
    - cron: '0 2 * * 1'  # Mondays 02:00 UTC
  workflow_dispatch:  # Manual trigger

jobs:
  rotate-fixtures:
    name: Rotate Frozen Fixtures
    runs-on: ubuntu-latest
    steps:
      - name: Check CI_SIGNER_PRIVKEY
        run: |
          if [ -z "${{ secrets.CI_SIGNER_PRIVKEY }}" ]; then
            echo "ERROR: CI_SIGNER_PRIVKEY secret is not set"
            exit 1
          fi
      
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      
      - name: Generate new fixture
        env:
          CI_SIGNER_PRIVKEY: ${{ secrets.CI_SIGNER_PRIVKEY }}
        run: |
          yarn hardhat run scripts/fixtures/generate.ts
          yarn ts-node scripts/freeze-fixture.ts
      
      - name: Check if fixture changed
        id: check-change
        run: |
          if git diff --quiet pricing-fixtures/ACME-LLC-30-frozen.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to frozen fixture"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Frozen fixture has changed"
          fi
      
      - name: Verify hash integrity
        if: steps.check-change.outputs.changed == 'true'
        run: yarn fixtures:hashcheck
      
      - name: Create Pull Request
        if: steps.check-change.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(fixtures): weekly frozen pricing refresh"
          title: "chore(fixtures): weekly frozen pricing refresh"
          body: |
            ## Weekly Fixture Rotation
            
            This PR updates the frozen pricing fixture as part of the weekly rotation schedule.
            
            ### Changes
            - Regenerated frozen fixture with fresh timestamp
            - Updated SHA256 hash for integrity verification
            
            ### New Hash
            ```bash
            $(cat pricing-fixtures/ACME-LLC-30-frozen.sha256)
            ```
            
            ### Verification
            - ✅ Fixture generated with pinned CI signer
            - ✅ Hash integrity verified
            - ✅ Replay tests will validate on merge
            
            Auto-generated by weekly fixture rotation workflow.
          branch: chore/fixtures-weekly-rotation
          delete-branch: true
          labels: fixtures,automated
          assignees: ${{ github.actor }}
