name: Weekly Fixture Rotation

on:
  schedule:
    - cron: '0 2 * * 1'  # Mondays 02:00 UTC
  workflow_dispatch:  # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rotate-fixtures:
    name: Rotate Frozen Fixtures
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Enable Corepack & pin Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version

      - name: Provide CI signer key (secret or fallback)
        run: |
          if [ -n "${{ secrets.CI_SIGNER_PRIVKEY }}" ]; then
            echo "CI_SIGNER_PRIVKEY=${{ secrets.CI_SIGNER_PRIVKEY }}" >> $GITHUB_ENV
            echo "Using CI_SIGNER_PRIVKEY from secrets"
          else
            echo "WARNING: CI_SIGNER_PRIVKEY not set; using dev fallback"
            echo "CI_SIGNER_PRIVKEY=0x59c6995e998f97a5a0044976f8a5b0e4d27dae8f8" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          yarn install --immutable
      
      - name: Generate new fixture
        env:
          CI_SIGNER_PRIVKEY: ${{ secrets.CI_SIGNER_PRIVKEY }}
        run: |
          yarn hardhat run scripts/fixtures/generate.ts
          yarn ts-node scripts/freeze-fixture.ts
      
      - name: Check if fixture changed
        id: check-change
        run: |
          if git diff --quiet pricing-fixtures/ACME-LLC-30-frozen.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes to frozen fixture"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Frozen fixture has changed"
          fi
      
      - name: Verify hash integrity
        if: steps.check-change.outputs.changed == 'true'
        run: yarn fixtures:hashcheck
      
      - name: Create Pull Request
        if: steps.check-change.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(fixtures): weekly frozen pricing refresh"
          title: "chore(fixtures): weekly frozen pricing refresh"
          body: |
            ## Weekly Fixture Rotation
            
            This PR updates the frozen pricing fixture as part of the weekly rotation schedule.
            
            ### Changes
            - Regenerated frozen fixture with fresh timestamp
            - Updated SHA256 hash for integrity verification
            
            ### New Hash
            ```bash
            $(cat pricing-fixtures/ACME-LLC-30-frozen.sha256)
            ```
            
            ### Verification
            - ✅ Fixture generated with pinned CI signer
            - ✅ Hash integrity verified
            - ✅ Replay tests will validate on merge
            
            Auto-generated by weekly fixture rotation workflow.
          branch: chore/fixtures-weekly-rotation
          delete-branch: true
          labels: fixtures,automated
          assignees: ${{ github.actor }}
