name: nightly-heavy-coverage

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"

jobs:
  heavy-coverage:
    name: Heavy Coverage (Shard ${{ matrix.shard }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        shard: [a, b]
    env:
      NODE_OPTIONS: --max_old_space_size=6144
      COVERAGE: "1"
      COVERAGE_HEAVY: "1"
      COVERAGE_SHARD: ${{ matrix.shard }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack + pin Yarn 4.9.2
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version

      - name: Cache Yarn Berry artifacts
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/patches
            .yarn/build-state.yml
            .pnp.cjs
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --immutable
      - run: yarn coverage:heavy

      - name: Enforce nightly coverage floor
        run: |
          NIGHTLY_FLOOR=$(node -pe "require('./ci/coverage-baseline.json').nightly_floor")
          bash scripts/check-coverage.sh "$NIGHTLY_FLOOR"

      - name: Ensure coverage artifacts exist
        if: always()
        run: |
          mkdir -p coverage
          echo '{"status": "coverage-completed"}' > coverage/placeholder.json

      - name: Upload heavy coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-heavy_${{ matrix.shard }}_${{ github.sha }}
          path: coverage/**
          retention-days: 14
